ElectroSterk.Web/Areas/Admin/Controllers/DashboardController.cs
using System.Web.Mvc;

namespace ElectroSterk.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

ElectroSterk.Web/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using System.Xml.Schema;
using DA;
using ElectroSterk.Web.Models;
using Entities;

namespace ElectroSterk.Web.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session["cart"] as List<Cart> ?? new List<Cart>();

            if (cart.Count == 0 || Session["cart"] == null)
            {
                ViewBag.Message = "Your cart is empty";
                return View();
            }

            decimal totla = 0m;
            foreach (var item in cart)
            {
                totla += item.Total;
            }

            ViewBag.GrandTotal = totla;

            return View(cart);
        }

        public ActionResult CartPartial()
        {
            Cart cart = new Cart();

            var quantity = 0;
            decimal price = 0m;

            if (Session["cart"] != null)
            {
                var list = (List<Cart>) Session["cart"];
                foreach (var item in list)
                {
                    quantity += item.Quantity;
                    price += item.Quantity * item.Price;
                }
                cart.Quantity = quantity;
                cart.Price = price;
            }
            else
            {
                cart.Quantity = 0;
                cart.Price = 0m;
            }

            return PartialView(cart);
        }

        public ActionResult AddToCartPartial(int id)
        {
            List<Cart> cart = Session["cart"] as List<Cart> ?? new List<Cart>();

            Cart model = new Cart();

            using (var db = new ElectroSterkDbContext())
            {
                Product product = db.Products.Find(id);

                var productInCart = cart.FirstOrDefault(x => x.ProductId == id);

                if (productInCart == null)
                {
                    cart.Add(new Cart()
                    {
                        ProductId = product.Id,
                        ProductName = product.Name,
                        Quantity = 1,
                        Price = product.Price,
                        Image = product.ImageName
                    });
                }
                else
                {
                    productInCart.Quantity++; 
                }
            }

            int quantity = 0;
            decimal price = 0m;

            foreach (var item in cart)
            {
                quantity += item.Quantity;
                price += item.Quantity * item.Price;
            }

            model.Quantity = quantity;
            model.Price = price;

            Session["cart"] = cart;

            return PartialView(model);
        }

        public JsonResult IncrementProduct(int productId)
        {
            List<Cart> cart = Session["cart"] as List<Cart>;

            using (var db = new ElectroSterkDbContext())
            {
                Cart model = cart.FirstOrDefault(x => x.ProductId == productId);

                model.Quantity++;
                var result = new {quantity = model.Quantity, price = model.Price};
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            
        }

        public JsonResult DecrementProduct(int productId)
        {
            List<Cart> cart = Session["cart"] as List<Cart>;

            using (var db = new ElectroSterkDbContext())
            {
                Cart model = cart.FirstOrDefault(x => x.ProductId == productId);

                if (model.Quantity > 1)
                {
                    model.Quantity--;
                }
                else
                {
                    model.Quantity = 0;
                    cart.Remove(model);
                }

                var result = new { quantity = model.Quantity, price = model.Price };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        public void RemoveProduct(int productId)
        {
            List<Cart> cart = Session["cart"] as List<Cart>;

            using (var db = new ElectroSterkDbContext())
            {
                Cart model = cart.FirstOrDefault(x => x.ProductId == productId);

                cart.Remove(model);
            }
        }

        public ActionResult PaypalPartial()
        {
            List<Cart> cart = Session["cart"] as List<Cart>;

            return PartialView(cart);
        }

        public void PlaceOrder()
        {
            List<Cart> cart = Session["cart"] as List<Cart>;

            string username = User.Identity.Name;

            int orderId = 0;

            using (var db = new ElectroSterkDbContext())
            {
                Order order = new Order();
                var user = db.OrderUsers.FirstOrDefault(x => x.UserName == username);
                int userId = user.Id;
                order.UserId = userId;
                order.CreatedOn = DateTime.Now;

                db.Orders.Add(order);
                db.SaveChanges();

                orderId = order.OrderId;

                OrderDetails orderDetails = new OrderDetails();

                foreach (var item in cart)
                {
                    orderDetails.OrderId = orderId;
                    orderDetails.UserId = userId;
                    orderDetails.ProductId = item.ProductId;
                    orderDetails.Quantity = item.Quantity;

                    db.OrderDetails.Add(orderDetails);

                    db.SaveChanges();
                }

            }

            //email 
            var client = new SmtpClient("smtp.mailtrap.io", 2525)
            {
                Credentials = new NetworkCredential("d0a13fae182e56", "759256fa7de8e5"),
                EnableSsl = true
            };
            client.Send("admin@example.com", "admin@example.com", "New Order", "You have a new order . order number is " + orderId);

            Session["cart"] = null;
        }
    }
}

ElectroSterk.Web/Controllers/PagesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DA;
using Entities;

namespace ElectroSterk.Web.Controllers
{
    public class PagesController : Controller
    {
        // GET: Index
        public ActionResult Index(string page = "")
        {
            if (page == "")
                page = "Home";
            Page modelPage ;

            using (var db = new ElectroSterkDbContext())
            {
                if (!db.Pages.Any(x => x.Title.Equals(page)))
                {
                    return RedirectToAction("Index", new { page = ""});
                }
            }

            using (var db = new ElectroSterkDbContext())
            {
                modelPage = db.Pages.FirstOrDefault(x => x.Title == page);
            }

            if (modelPage != null)
            {
                ViewBag.PageTitle = modelPage.Title;
            }

            if (modelPage.HasSidbar)
            {
                ViewBag.Sidebar = "Yes";
            }
            else
            {
                ViewBag.Sidebar = "No";
            }
            return View(modelPage);
        }

        public ActionResult PagesMenuPartial()
        {
            List<Page> pageList;
            using (var db = new ElectroSterkDbContext())
            {
                pageList = db.Pages.ToArray().OrderBy(x => x.Sorting).Where(x => x.Title != "Home").ToList();
            }

            return PartialView(pageList);
        }

        public ActionResult SidebarPartial()
        {
            Sidebar sidebar;

            using (var db = new ElectroSterkDbContext())
            {
                sidebar = db.Sidebars.Find(1);
            }

            return PartialView(sidebar);
        }

        public ActionResult HomePagePartial()
        {
            return PartialView();
        }
    }
}

ElectroSterk.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ElectroSterk</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand "> <img id="logo" src="~/Content/img/logo.png" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.Action("PagesMenuPartial", "Pages");
                </ul>
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <ul class="adminarea navbar-collapse collapse navbar-right">
                        <li>@Html.ActionLink("Admin Area", "Index","Dashboard", new {area = "Admin"},null)</li>
                    </ul>
                }
                else
                {
                    if ((ViewBag.Title != "Cart Details") && Request.IsAuthenticated && User.IsInRole("User"))
                    {
                        <ul class="navbar-collapse collapse navbar-right">
                            @Html.Action("CartPartial", "Cart")
                        </ul>
                    }

                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="ajaxbg"><span><img src="~/Content/img/ajax-loader.gif" /></span></div>

            @if (ViewBag.Title != "Register" &&
                 ViewBag.Title != "Log in" &&
                 ViewBag.Title != "Manage" &&
                 ViewBag.Title != "Orders")

            {
                <div class="col-xs-12 col-md-2">
                    @Html.Action("CategoryMenuPartial", "Shop")
                </div>
            }

            @if (ViewBag.Title == "Home")
            {
                <div class="col-xs-12 col-md-10">
                    @Html.Action("HomePagePartial", "Pages")
                </div>
            }

            @if (ViewBag.Title == "Manage")
            {
                <div class="col-xs-12 col-md-2">
                    <ul>
                        <li><a href="/account/orders">Mijn bestellingen</a></li>
                    </ul>
                </div>
            }

            @if (ViewBag.Title == "Orders")
            {
                <div class="col-xs-12 col-md-2">
                    <ul>
                        <li><a href="/Manage/Index">Mijn account</a></li>
                    </ul>
                </div>
            }

            @if (ViewBag.Sidebar == "Yes")
            {
                <div class="col-xs-12 col-md-7">
                    @RenderBody()
                </div>
                <div class="col-xs-12 col-md-3">
                    @Html.Action("SidebarPartial", "Pages");
                </div>
            }
            else
            {
                <div class="col-xs-12 col-md-10">
                    @RenderBody()
                </div>
            }
        </div>

        <hr />
        <div class="row">
            <div class="col-xs-12 col-md-4 div-footer">
                <div class="">
                    <h4>Hulp nodig?</h4>
                    <ul class="ul-footer">
                        <li><a href="#">Hulp & vragen</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">Terugsturen & Omruilen</a></li>
                        <li><a href="#">Voorwaarden</a></li>
                        <li><a href="#">Afhalen</a></li>
                        <li><a href="#">Levering</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-12 col-md-4 div-footer">
                <div class="">
                    <h4>Electrosterk</h4>
                    <ul class="ul-footer">
                        <li><a href="#">Wie zijn wij?</a></li>
                        <li><a href="#">Privacybeleid</a></li>
                        <li><a href="#">Zakelijk</a></li>
                        <li><a href="#">Winkels</a></li>
                        <li><a href="#">Pers</a></li>
                        <li><a href="#">Jobs</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-12 col-md-4 div-footer">
                <div class="">
                    <h4>Volg ons</h4>
                </div>
                <div>
                    <h4>Download ons</h4>
                    <img src="~/Content/img/app-store.png" /> <br /> <br />
                    <img src="~/Content/img/google-play.png" />
                </div>
            </div>
        </div>
        <hr />
        <footer>
            <p><img src="~/Content/img/home-images/payments-card.JPG" style="width: 100%;" /></p>
            <p class="text-center">&copy; @DateTime.Now.Year - ElectroSterk</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
</body>
</html>